### ISSUE TITLE
aws-kinesis-spark Error 

### ISSUE THREAD

**Issue by vilaspmahajan** [bizreach/aws-kinesis-scala#19]
hi team,

please help code is.

--------------------------------------------------
import jp.co.bizreach.kinesis.spark._
import com.amazonaws.regions.Regions

val lines = sc.parallelize(List("pandas", "i like pandas"))
println(lines.count)
lines.saveToKinesis(
  streamName = "arn:aws:kinesis:us-east-1:96833sdsd6292411:stream/XXXXX",
  region     = Regions.US_EAST_1,
  chunk      = 30
)
---------------------------------------------------
Error 
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 7.0 failed 4 times, most recent failure: Lost task 0.3 in stage 7.0 (TID 39, ip-172-31-29-9.ap-southeast-1.compute.internal, executor 2): com.amazonaws.services.kinesis.model.AmazonKinesisException: 1 validation error detected: Value 'arn:aws:kinesis:us-east-1:968336292dfd411:stream/XXXXX' at 'streamName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+ (Service: AmazonKinesis; Status Code: 400; Error Code: ValidationException; Request ID: c99b02dd-4f09-ac0d-9be5-3b83a256719b)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1592)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2219)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2195)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executePutRecords(AmazonKinesisClient.java:1697)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:1673)
	at jp.co.bizreach.kinesis.AmazonKinesis$$anonfun$putRecordsWithRetry$1.apply(AmazonKinesis.scala:127)
	at jp.co.bizreach.kinesis.AmazonKinesis$$anonfun$putRecordsWithRetry$1.apply(AmazonKinesis.scala:126)
	at jp.co.bizreach.kinesis.action.PutRecordAction$class.put0$1(PutRecordAction.scala:26)
	at jp.co.bizreach.kinesis.action.PutRecordAction$class.withPutsRetry(PutRecordAction.scala:40)
	at jp.co.bizreach.kinesis.AmazonKinesis$$anon$2.withPutsRetry(AmazonKinesis.scala:17)
	at jp.co.bizreach.kinesis.AmazonKinesis.putRecordsWithRetry(AmazonKinesis.scala:126)
	at jp.co.bizreach.kinesis.spark.KinesisRDDWriter$$anonfun$1.jp$co$bizreach$kinesis$spark$KinesisRDDWriter$$anonfun$$put$1(KinesisRDDWriter.scala:22)
	at jp.co.bizreach.kinesis.spark.KinesisRDDWriter$$anonfun$1.apply(KinesisRDDWriter.scala:45)
	at jp.co.bizreach.kinesis.spark.KinesisRDDWriter$$anonfun$1.apply(KinesisRDDWriter.scala:18)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by shimamoto** [comment]
@vilaspmahajan You specify the stream name instead of the ARN for the `streamName` argument of the `saveToKinesis` method. For example, if the ARN is following:

```
arn:aws:kinesis:us-east-1:111122223333:stream/my-stream
```

then you specify the `my-stream`.

**Comment by l0n3r4n83r** [comment]
@shimamoto how should one handle when the kinesis stream belongs to another AWS account ?

**Comment by shimamoto** [comment]
@l0n3r4n83r You probably need to use AWSCredentialsProvider implementation (e.g. STSAssumeRoleSessionCredentialsProvider) that uses the AWS STS, but as you say, the current version cannot handle the AWS STS because the credentials parameter of saveToKinesis method is only a class type.

**Comment by bobRafat** [comment]
is there a way to publish messages to another AWS account?

**Comment by l0n3r4n83r** [comment]
> is there a way to publish messages to another AWS account?
Yes it was added in https://github.com/bizreach/aws-kinesis-scala/pull/24
