### ISSUE TITLE
java.lang.NoClassDefFoundError on saveToKinesis

### ISSUE THREAD

**Issue by l0n3r4n83r** [bizreach/aws-kinesis-scala#20]
I am running this code inside databricks and getting a class not found error.

```
val row = Array("payload")

val rdd = spark.sparkContext.parallelize(row)
rdd.saveToKinesis(
  streamName = "my-stream-name",
  region     = Regions.US_WEST_1,
  chunk      = 30
)
```
I do have aws-kinesis-scala and aws-kinesis-spark jars attached to my cluster.

```
Caused by: java.lang.NoClassDefFoundError: jp/co/bizreach/kinesis/package$PutRecordsEntry
	at jp.co.bizreach.kinesis.spark.KinesisRDDWriter$$anonfun$1$$anonfun$2.apply(KinesisRDDWriter.scala:30)
	at jp.co.bizreach.kinesis.spark.KinesisRDDWriter$$anonfun$1$$anonfun$2.apply(KinesisRDDWriter.scala:27)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at org.apache.spark.InterruptibleIterator.foldLeft(InterruptibleIterator.scala:28)
	at jp.co.bizreach.kinesis.spark.KinesisRDDWriter$$anonfun$1.apply(KinesisRDDWriter.scala:27)
	at jp.co.bizreach.kinesis.spark.KinesisRDDWriter$$anonfun$1.apply(KinesisRDDWriter.scala:18)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by l0n3r4n83r** [comment]
Only one jar needs to be attached removing one of the jars from the classpath worked.
